### Hi there 👋


**gurkanguldas/gurkanguldas** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

![gurkanguldas](https://github-readme-stats.vercel.app/api/top-langs?username=gurkanguldas&show_icons=true&locale=en&layout=compact) 

![gurkanguldas](https://github-readme-stats.vercel.app/api?username=gurkanguldas&count_private=true&show_icons=true&icon_color=ce7e00)
